enum Events {
	GET_ALL_PLACES = "GET_ALL_PLACES",
    GET_ALL_PLACES_FULFILLED = "GET_ALL_PLACES_FULFILLED",
    GET_ALL_PLACES_REJECTED = "GET_ALL_PLACES_REJECTED",
    CLEAR_GET_ALL_PLACES = "CLEAR_GET_ALL_PLACES",
    GET_PLACE_DATA = "GET_PLACE_DATA",
    GET_PLACE_DATA_FULFILLED = "GET_PLACE_DATA_FULFILLED",
    GET_PLACE_DATA_REJECTED = "GET_PLACE_DATA_REJECTED",
    CLEAR_GET_PLACE_DATA = "CLEAR_GET_PLACE_DATA",
}
export default Events;